products:
  conjure-plugin:
    build:
      main-pkg: .
      environment:
        CGO_ENABLED: "0"
      os-archs:
      - os: darwin
        arch: amd64
      - os: linux
        arch: amd64
      version-var: github.com/palantir/godel-conjure-plugin/cmd.Version
    dist:
      disters:
        type: os-arch-bin
        config:
          os-archs:
            - os: darwin
              arch: amd64
            - os: linux
              arch: amd64
    publish: {}
product-defaults:
  publish:
    group-id: com.palantir.godel-conjure-plugin
